### ISSUE TITLE
Task 2: API constructors and load methods

### ISSUE THREAD

**Issue by left-over-dinner** [luyongtang/Summer_2018_Project#2]
1. Create an object with two constructors. The first constructor takes no parameters while the second constructor takes an ID, which is the id of the DIV where the map should be loaded.

2. Add the method setMap(ID): saves the ID received received from the paramater,  of the DIV where the map should be loaded.

3. Add .load() method: This method loads the map using the ID (received earlier by the 2nd constructor or setMap() method

**Comment by luyongtang** [comment]
The first two subtasks are completed and the functionality is tested in driver.js.
Load() method is not done and I have no idea about that for now. Please advise. Thank you!

**Comment by left-over-dinner** [comment]
Great! I have made progress on top of your code. The .load() is changed to .loadMap() and is properly working. The callback function from Google Maps link is the function to be called once Google Maps has been loaded. From there, in that function we add the .loadMap() since now the Google Maps has been fully loaded.
